version: "3.9"

services:
    server:
        image: emsoftmm/zol-server:v1. # name of docker container 
        build: .
        ports:
            - "80:5000"
    db:
        image: "postgres"
        ports:
            - "80:5432"
        environment:
            POSTGRES_PASSWORD: "future"
            POSTGRES_USER: "docker"
        volumes:
            - data:/var/lib/postgresql/data

volumes:
    data:
