version: "3.9"

services:
    db:
        image: "postgres"
        restart: always
        ports:
            - "4321:5432"
        environment:
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_USER: ${PG_USER}
        volumes:
            - data:/var/lib/postgresql/data
    server:
        image: zoolbiaserver001 # name of docker container
        build: .
        depends_on:
            - db
        ports:
            - "3000:3000"
            - "5051:5051"
        environment:
            PG_USER: ${PG_USER}
            PG_HOST: ${PG_HOST} # db 
            PG_DB: ${PG_DB}
            PG_PASS: ${PG_PASS}
            PG_PORT: ${PG_PORT}
        links:
            - db
        volumes:
            - './:/src'

volumes:
    data:
